"""initial_schema

Revision ID: 79aa41e12d56
Revises: 
Create Date: 2026-04-25 17:32:26.723555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79aa41e12d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_activity_user_time', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_activity_user_type', 'activity_logs', ['user_id', 'action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.add_column('streaks', sa.Column('freeze_count', sa.Integer(), nullable=True))
    op.add_column('task_completions', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index('idx_completions_task_user', 'task_completions', ['task_id', 'user_id'], unique=False)
    op.create_index('idx_completions_user_date', 'task_completions', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_completions_user_id'), 'task_completions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'task_completions', ['idempotency_key'])
    op.create_index(op.f('ix_task_schedules_task_id'), 'task_schedules', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_tasks_user_active', 'tasks', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.add_column('user_stats', sa.Column('consistency_index', sa.Float(), nullable=True))
    op.add_column('user_stats', sa.Column('total_completions', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_active')
    op.drop_column('user_stats', 'updated_at')
    op.drop_column('user_stats', 'total_completions')
    op.drop_column('user_stats', 'consistency_index')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('idx_tasks_user_active', table_name='tasks')
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'deleted_at')
    op.drop_index(op.f('ix_task_schedules_task_id'), table_name='task_schedules')
    op.drop_constraint(None, 'task_completions', type_='unique')
    op.drop_index(op.f('ix_task_completions_user_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index('idx_completions_user_date', table_name='task_completions')
    op.drop_index('idx_completions_task_user', table_name='task_completions')
    op.drop_column('task_completions', 'idempotency_key')
    op.drop_column('streaks', 'freeze_count')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_index('idx_activity_user_type', table_name='activity_logs')
    op.drop_index('idx_activity_user_time', table_name='activity_logs')
    # ### end Alembic commands ###
