"""add_task_skips_weekly_analytics

Revision ID: e8ccbc70b686
Revises: 79aa41e12d56
Create Date: 2026-04-25 17:42:16.210508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ccbc70b686'
down_revision: Union[str, Sequence[str], None] = '79aa41e12d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_analytics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('skips', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('consistency_index_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weekly_user_week', 'weekly_analytics', ['user_id', 'week_start'], unique=False)
    op.create_index(op.f('ix_weekly_analytics_user_id'), 'weekly_analytics', ['user_id'], unique=False)
    op.create_table('task_skips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('skipped_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skips_task_user', 'task_skips', ['task_id', 'user_id'], unique=False)
    op.create_index('idx_skips_user_date', 'task_skips', ['user_id', 'skipped_date'], unique=False)
    op.create_index(op.f('ix_task_skips_task_id'), 'task_skips', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_skips_user_id'), 'task_skips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_skips_user_id'), table_name='task_skips')
    op.drop_index(op.f('ix_task_skips_task_id'), table_name='task_skips')
    op.drop_index('idx_skips_user_date', table_name='task_skips')
    op.drop_index('idx_skips_task_user', table_name='task_skips')
    op.drop_table('task_skips')
    op.drop_index(op.f('ix_weekly_analytics_user_id'), table_name='weekly_analytics')
    op.drop_index('idx_weekly_user_week', table_name='weekly_analytics')
    op.drop_table('weekly_analytics')
    # ### end Alembic commands ###
