export const TASK_TEMPLATES: Record<string, { title: string; difficulty: number; sensor: string; target: number | null; minutes: number | null }[]> = {
  fitness: [
    { title: '10,000 steps daily',     difficulty: 3, sensor: 'steps', target: 10000, minutes: 90 },
    { title: '5km run',                difficulty: 3, sensor: 'steps', target: 5000,  minutes: 30 },
    { title: '100 pushups',            difficulty: 4, sensor: 'reps',  target: 100,   minutes: 20 },
    { title: '50 squats',              difficulty: 2, sensor: 'reps',  target: 50,    minutes: 10 },
    { title: '30 min workout',         difficulty: 3, sensor: 'timer', target: 30,    minutes: 30 },
    { title: '20 min yoga',            difficulty: 2, sensor: 'timer', target: 20,    minutes: 20 },
    { title: '50 burpees',             difficulty: 4, sensor: 'reps',  target: 50,    minutes: 15 },
    { title: '15,000 steps challenge', difficulty: 4, sensor: 'steps', target: 15000, minutes: 120 },
  ],
  mindfulness: [
    { title: '30 min meditation',    difficulty: 2, sensor: 'timer', target: 30,  minutes: 30 },
    { title: '10 min breathing',     difficulty: 1, sensor: 'timer', target: 10,  minutes: 10 },
    { title: 'Gratitude journaling', difficulty: 1, sensor: 'none',  target: null, minutes: 10 },
    { title: '20 min yoga flow',     difficulty: 2, sensor: 'timer', target: 20,  minutes: 20 },
    { title: 'Digital detox 1 hour', difficulty: 3, sensor: 'timer', target: 60,  minutes: 60 },
    { title: 'Evening reflection',   difficulty: 1, sensor: 'none',  target: null, minutes: 10 },
    { title: 'Cold shower',          difficulty: 3, sensor: 'none',  target: null, minutes: 5  },
    { title: '5 min mindful walk',   difficulty: 1, sensor: 'timer', target: 5,   minutes: 5  },
  ],
  learning: [
    { title: '45 min study session',   difficulty: 3, sensor: 'timer', target: 45,  minutes: 45 },
    { title: 'Read for 30 minutes',    difficulty: 2, sensor: 'timer', target: 30,  minutes: 30 },
    { title: '1 hour deep work',       difficulty: 4, sensor: 'timer', target: 60,  minutes: 60 },
    { title: 'Learn 10 new words',     difficulty: 2, sensor: 'none',  target: null, minutes: 15 },
    { title: 'Practice coding 1 hour', difficulty: 3, sensor: 'timer', target: 60,  minutes: 60 },
    { title: 'Write 500 words',        difficulty: 3, sensor: 'none',  target: null, minutes: 30 },
    { title: 'Review flashcards',      difficulty: 1, sensor: 'none',  target: null, minutes: 15 },
    { title: 'Watch 1 lecture',        difficulty: 2, sensor: 'none',  target: null, minutes: 45 },
  ],
  diet: [
    { title: '8 glasses of water',    difficulty: 2, sensor: 'water', target: 8,    minutes: null },
    { title: 'No sugar today',        difficulty: 3, sensor: 'none',  target: null, minutes: null },
    { title: 'Eat 5 servings of veg', difficulty: 2, sensor: 'none',  target: null, minutes: null },
    { title: 'Drink 3L water',        difficulty: 3, sensor: 'water', target: 10,   minutes: null },
    { title: 'No processed food',     difficulty: 3, sensor: 'none',  target: null, minutes: null },
    { title: 'Meal prep Sunday',      difficulty: 2, sensor: 'none',  target: null, minutes: 60  },
    { title: 'Intermittent fast 16h', difficulty: 4, sensor: 'none',  target: null, minutes: null },
    { title: 'Protein at breakfast',  difficulty: 2, sensor: 'none',  target: null, minutes: null },
  ],
  productivity: [
    { title: 'Morning routine',        difficulty: 2, sensor: 'none',  target: null, minutes: 30  },
    { title: 'Inbox zero',             difficulty: 2, sensor: 'none',  target: null, minutes: 20  },
    { title: 'Plan tomorrow tonight',  difficulty: 1, sensor: 'none',  target: null, minutes: 10  },
    { title: '2 hour focus block',     difficulty: 4, sensor: 'timer', target: 120,  minutes: 120 },
    { title: 'No phone before 9am',    difficulty: 3, sensor: 'none',  target: null, minutes: null },
    { title: 'Weekly review',          difficulty: 2, sensor: 'none',  target: null, minutes: 30  },
    { title: 'Clear desk before bed',  difficulty: 1, sensor: 'none',  target: null, minutes: 5   },
    { title: '3 most important tasks', difficulty: 2, sensor: 'none',  target: null, minutes: 60  },
  ],
  other: [
    { title: '30 min meditation',    difficulty: 2, sensor: 'timer', target: 30,  minutes: 30 },
    { title: '10,000 steps daily',   difficulty: 3, sensor: 'steps', target: 10000, minutes: 90 },
    { title: 'Read for 30 minutes',  difficulty: 2, sensor: 'timer', target: 30,  minutes: 30 },
    { title: '8 glasses of water',   difficulty: 2, sensor: 'water', target: 8,   minutes: null },
    { title: 'Morning routine',      difficulty: 2, sensor: 'none',  target: null, minutes: 30 },
    { title: 'Gratitude journaling', difficulty: 1, sensor: 'none',  target: null, minutes: 10 },
    { title: '30 min workout',       difficulty: 3, sensor: 'timer', target: 30,  minutes: 30 },
    { title: 'Plan tomorrow tonight',difficulty: 1, sensor: 'none',  target: null, minutes: 10 },
  ],
};
